# Generated by Django 5.0.7 on 2024-07-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_followercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followercount',
            old_name='postId',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='followercount',
            old_name='username',
            new_name='user',
        ),
    ]
